---
title: About
output:
  html_document:
    includes:
       in_header: GA_Script.html
---

I am Brian O'Meara, a resident of Oak Ridge, TN. This site used to be a single long page on my http://www.brianomeara.info personal website, but it seemed easier to make it a separate site with bookmarkable pages. You can see all the code used to make this site at https://github.com/bomeara/EastTN. Note that while I work in science, I am not an expert in epidemiology; this is just a compilation of others' data. Talk to your doctor for making health decisions.

Some of the data sources:

* [Knox County Health Department](https://covid.knoxcountytn.gov/)
* [Oak Ridge Schools](https://www.ortn.edu/covid-information/)
* [Knox County Schools](https://www.knoxschools.org/covid)
* [UT Knoxville](https://www.utk.edu/coronavirus/guides/data-monitoring-and-contingency-options/)
* [Alex Zukowski Dashboard](https://sites.google.com/view/utk-covid19)
* [Tennessee Department of Health](https://www.tn.gov/health/cedep/ncov/data/downloadable-datasets.html)
* [COVID-19 Forecast Hub](https://covid19forecasthub.org)
* [US Health and Human Services](https://healthdata.gov)

Some of the tools used:

* [R](https://www.r-project.org/) along with [many R packages](https://github.com/bomeara/EastTN/blob/main/_packages.R)
* [github](https://github.com) for hosting
* [wget](https://www.gnu.org/software/wget/) and [curl](https://curl.haxx.se/) for downloading data
* [ScrapingAnt](https://scrapingant.com/) for particularly difficult to parse pages

As part of this, I compile the data from different days and organize it into spreadsheets. You can download them below. Note that these involve transformations of the original data (i.e., I might have to download a page, parse it, and then transform it into a spreadsheet), which is done as accurately as I can, but there could still be errors. Each sheet typically has a date column; for the cases by individual school districts, the date is when the data were downloaded, but could reflect the previous day's information.

* [Focal data for our region (cases, vaccination)](daily_focal.csv)
* [Cases in students in region](schoolkids_daily_out.csv)
* [Oak Ridge student cases](schools_oakridge.csv)
* [Knox County student cases](schools_knox.csv)
* [Knox County cases by school](individual_schools_knox.csv)
* [Hospitalization data (includes ICUs, ventilators)](hospital_knox.csv)

Remember we are still in a pandemic. **Get vaccinated to keep others and yourself safe: https://www.vaccines.gov/ to find vaccines**.