---
title: Knox County Schools
output: html_document
---

Knox County Schools are releasing information at https://www.knoxschools.org/covid, I take a snapshot of this every 24 hours and plot it.

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.alt="Line plot of active covid cases"}

source("_packages.R")
tar_load(schools_knox)
schools_knox_counts <- data.frame(Date=rep(schools_knox$Date,2), Count=c(schools_knox$Active_Students_Count, schools_knox$Active_Staff_Count), Population=c(rep("Student", nrow(schools_knox)), rep("Staff", nrow(schools_knox))))


try(knox_schools_ytd <- ggplot(schools_knox_counts, aes(x=Date, y=Count, group=Population)) + geom_line(aes(colour=Population)) + theme_light() + ylab("Number of individuals with active covid infections") + xlab("Date") + ggtitle("Counts of covid infections in Knox County Schools, TN"))
print(knox_schools_ytd)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.alt="Line plot of active covid cases now in Oak Ridge schools"}


schools_knox_percent <- data.frame(Date=rep(schools_knox$Date,2), Percent=c(schools_knox$Active_Students_Percent, schools_knox$Active_Staff_Percent), Population=c(rep("Student", nrow(schools_knox)), rep("Staff", nrow(schools_knox))))



try(knox_schools_pct <- ggplot(schools_knox_percent, aes(x=Date, y=Percent, group=Population)) + geom_line(aes(colour=Population)) + theme_light() + ylab("Percent of individuals with active covid infections") + xlab("Date") + ggtitle("Percentage of covid infections in Knox County Schools, TN"))
print(knox_schools_pct)
```

I also maintain [vaccication.org](http://vaccication.org). This has information about vaccination in various US counties; below is the page for Knox County. Pay special note to the vaccination rate for those age 12-18.

<iframe src='https://vaccication.org/counties/Knox_TN.html' width="100%" height=1600></iframe>