---
title: Risk by Activity
output:
  html_document:
    includes:
       in_header: GA_Script.html
---


The [microCOVID Project](https://microcovid.org/) is a service that uses the best available data to estimate the risk of different activities. It does not replace advice from a medical professional, but as a way to deciding how to balance risk, it can be useful. It computes "microcovids," a one in a million chance of getting covid: every 10,000 microcovids means a 1% chance of getting covid at the event. I created a set of scenarios that may represent potential events in East Tennessee; for each one, the expected probability of getting covid at that event per event, based on microcovid's data, is shown. For each, the risk is shown for someone vaccinated and masked, vaccinated but not masked, and not vaccinated nor masked. You can go to the linked page for each to change the parameters. These numbers are as of Sept. 9, 2021.

Microcovid.org's point estimate of probability of getting covid at each of these events:

```{r table2, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
tabl <- "
| **Scenario** | **Masked & Vaxed** | **Masked, Not Vaxed** |  **Not Vaxed & Not Masked** |
| -------- | -------------------- | -------------------- | -------------------- |
| In outdoor stadium or bleachers, others unmasked  | [1%](https://www.microcovid.org/?distance=normal&duration=180&interaction=oneTime&personCount=15&riskProfile=bars&scenarioName=custom&setting=outdoor&subLocation=US_47093&theirMask=none&topLocation=US_47&voice=normal&yourMask=basic&yourVaccineDoses=2&yourVaccineType=pfizer) | [7%](https://www.microcovid.org/?distance=normal&duration=180&interaction=oneTime&personCount=15&riskProfile=bars&scenarioName=custom&setting=outdoor&subLocation=US_47093&theirMask=none&topLocation=US_47&voice=normal&yourMask=basic) | [10%](https://www.microcovid.org/?distance=normal&duration=180&interaction=oneTime&personCount=15&riskProfile=bars&scenarioName=custom&setting=outdoor&subLocation=US_47093&theirMask=none&topLocation=US_47&voice=normal&yourMask=none) |
| Grocery Store for 60 minutes, others unmasked | [0.02%](https://www.microcovid.org/?distance=sixFt&duration=60&interaction=oneTime&personCount=5&riskProfile=average&scenarioName=60minShopping&setting=indoor&subLocation=US_47093&theirMask=none&topLocation=US_47&voice=silent&yourMask=basic&yourVaccineDoses=2&yourVaccineType=pfizer) | [0.10%](https://www.microcovid.org/?distance=sixFt&duration=60&interaction=oneTime&personCount=5&riskProfile=average&scenarioName=60minShopping&setting=indoor&subLocation=US_47093&theirMask=none&topLocation=US_47&voice=silent&yourMask=basic) | [0.20%](https://www.microcovid.org/?distance=sixFt&duration=60&interaction=oneTime&personCount=5&riskProfile=average&scenarioName=60minShopping&setting=indoor&subLocation=US_47093&theirMask=none&topLocation=US_47&voice=silent&yourMask=none) |
| Packed in room (lecture, performance, etc.), others unmasked  | [1%](https://www.microcovid.org/?distance=close&duration=60&interaction=oneTime&personCount=15&riskProfile=average&scenarioName=custom&setting=indoor&subLocation=US_47093&theirMask=none&topLocation=US_47&voice=normal&yourMask=basic&yourVaccineDoses=2&yourVaccineType=pfizer) | [7%](https://www.microcovid.org/?distance=close&duration=60&interaction=oneTime&personCount=15&riskProfile=average&scenarioName=custom&setting=indoor&subLocation=US_47093&theirMask=none&topLocation=US_47&voice=normal&yourMask=basic) | [10%](https://www.microcovid.org/?distance=close&duration=60&interaction=oneTime&personCount=15&riskProfile=average&scenarioName=custom&setting=indoor&subLocation=US_47093&theirMask=none&topLocation=US_47&voice=normal&yourMask=none) |
| Packed in room (lecture, performance, etc.), others masked  | [0.4%](https://www.microcovid.org/?distance=close&duration=60&interaction=oneTime&personCount=15&riskProfile=average&scenarioName=custom&setting=indoor&subLocation=US_47093&theirMask=basic&topLocation=US_47&voice=normal&yourMask=basic&yourVaccineDoses=2&yourVaccineType=pfizer) | [2.0%](https://www.microcovid.org/?distance=close&duration=60&interaction=oneTime&personCount=15&riskProfile=average&scenarioName=custom&setting=indoor&subLocation=US_47093&theirMask=basic&topLocation=US_47&voice=normal&yourMask=basic) | [3.0%](https://www.microcovid.org/?distance=close&duration=60&interaction=oneTime&personCount=15&riskProfile=average&scenarioName=custom&setting=indoor&subLocation=US_47093&theirMask=basic&topLocation=US_47&voice=normal&yourMask=none) |
| Going to a bar | [30%](https://www.microcovid.org/?distance=sixFt&duration=120&interaction=oneTime&personCount=15&riskProfile=bars&scenarioName=bar&setting=indoor&subLocation=US_47093&theirMask=none&topLocation=US_47&voice=loud&yourMask=basic&yourVaccineDoses=2&yourVaccineType=pfizer) | [91%](https://www.microcovid.org/?distance=sixFt&duration=120&interaction=oneTime&personCount=15&riskProfile=bars&scenarioName=bar&setting=indoor&subLocation=US_47093&theirMask=none&topLocation=US_47&voice=loud&yourMask=basic&yourVaccineDoses=2) | [96%](https://www.microcovid.org/?distance=sixFt&duration=120&interaction=oneTime&personCount=15&riskProfile=bars&scenarioName=bar&setting=indoor&subLocation=US_47093&theirMask=none&topLocation=US_47&voice=loud&yourMask=none&yourVaccineDoses=2) |"
cat(tabl)
```

Remember that these are *per event* probabilities. So if you have something that has a 3% risk, then the odds you don't get covid doing it once is 97%. But the odds of not getting covid three times in a row is 97% times 97% times 97%, which is 91% (so the odds of getting covid at some point by doing this activity on three occasions is 9%). If you were to do this activity 10 times, the chance of getting covid at least once is 100% - 97% ^ 10 = 26%, even though the chance in each occurrence is only 3%. 