---
title: Travel
output:
  html_document:
    includes:
       in_header: GA_Script.html
---


```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("_packages.R")
source("R/functions.R")
tar_load(tsa_throughput)
```

Here are TSA screenings nationwide over time, pulled from https://www.tsa.gov/coronavirus/passenger-throughput. 

```{r tsa_screenings, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
plot_tsa <- ggplot(tsa_throughput, aes(x=Date, y=Throughput)) + geom_line()+ theme_light() + xlab("Date") + ylab("Number of Screened Passengers")
print(plot_tsa)
```

Travel volume differs by day of week. Here, we're comparing 2019 vs 2021 (as travel picks back up). 

```{r tsa_day_of_week, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
tsa_throughput$Day <- weekdays(tsa_throughput$Date)
tsa_throughput$Year <- format(tsa_throughput$Date, "%Y")

tsa_throughput$Day <- factor(tsa_throughput$Day, c( "Monday", "Tuesday", "Wednesday", "Thursday","Friday", "Saturday", "Sunday"))
plot_tsa_day <- ggplot(subset(tsa_throughput, Year!="2020"), aes(x=Day , y=Throughput, fill=Year)) + geom_boxplot()+ theme_light() + xlab("Day") + ylab("Number of Screened Passengers")
print(plot_tsa_day)
```