---
title: Vaccination
output:
  html_document:
    includes:
       in_header: GA_Script.html
---


## No more data

July 27, 2023: The data sources I was using for this site are no longer being updated. The only remaining sources seem to be sewage data; CDC has it [https://covid.cdc.gov/covid-data-tracker/#wastewater-surveillance](here) but it's all relative (Covid levels in sewage versus the highest at any point at that site, but sites came online at different times). Biobot Analytics has data on absolute numbers through time (as well as variants) [https://biobot.io/data/covid-19](here) but they no longer have freely accessible raw data. Even hospitals release data only sporadically and incompletely now. I might poke around later to see what's available but for now I'm not updating this site.

### Old site


Tennessee releases information on demographics of individuals getting vaccinated. All terminology follows that used by the state, including terms like race and sex. The way the census and Tennessee count individuals who identify as not being in Asian, White, or Black or African American groups (people who are multiracial, Native American, Pacific Islander, other) seems to differ in ways that make calculating the percentage of members of the these groups difficult; the same happens for people who do not identify as male or female.

```{r vaccination1, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
source("_packages.R")
tar_load(covid_by_demographic_in_tn)
race <- covid_by_demographic_in_tn$race
ethnicity <- covid_by_demographic_in_tn$ethnicity
sex <- covid_by_demographic_in_tn$sex
race_vaccine <- covid_by_demographic_in_tn$race_vaccine
ethnicity_vaccine <- covid_by_demographic_in_tn$ethnicity_vaccine
sex_vaccine <- covid_by_demographic_in_tn$sex_vaccine


plot_race_covid_vaccination_full <- ggplot(race_vaccine, aes(x=DATE, y=PercentFullyVaccinated, group=Race)) + geom_line(aes(colour=Race))+ xlab("Date") + ylim(0,100) + theme_light() + ylab("Percentage of people fully vaccinated")  + theme(legend.justification = c(1, 1), legend.position = c(1, 1))
print(plot_race_covid_vaccination_full)

plot_ethnicity_covid_vaccination_full <- ggplot(ethnicity_vaccine, aes(x=DATE, y=PercentFullyVaccinated, group=Ethnicity)) + geom_line(aes(colour=Ethnicity))+ xlab("Date") + theme_light() + ylim(0,100) + ylab("Percentage of people fully vaccinated") + theme(legend.justification = c(1, 1), legend.position = c(1, 1))
print(plot_ethnicity_covid_vaccination_full)

plot_sex_covid_vaccination_full <- ggplot(sex_vaccine, aes(x=DATE, y=PercentFullyVaccinated, group=Sex)) + geom_line(aes(colour=Sex))+ xlab("Date") + theme_light() + ylim(0,100) + ylab("Percentage of people fully vaccinated")  + theme(legend.justification = c(1, 1), legend.position = c(1, 1))
print(plot_sex_covid_vaccination_full)

#vax_plot <- ggarrange(plot_race_covid_vaccination_full, plot_ethnicity_covid_vaccination_full, plot_sex_covid_vaccination_full, labels=c("", "", ""), ncol=3, nrow=1)
#print(vax_plot)
```
